### ISSUE TITLE
CanalSharp是否支持全量更新?

### ISSUE THREAD

**Issue by wmowm** [dotnetcore/CanalSharp#112]
在使用CanalSharp监听的时候,只能获取到增量数据,能否支持全量更新?先同步历史数据,然后再增量更新?

**Comment by Sheldon-NULL** [comment]
@wmowm 
这个应该跟客户端没啥关系~
你可以在Canal那边做文章，把相关数据文件全部删掉，Binlog解析节点配置那里改到初始位置。重新启动即可
