### ISSUE TITLE
canalsharp目前支持多个canal instance么？

### ISSUE THREAD

**Issue by pinopino** [dotnetcore/CanalSharp#40]
比如我线上有三台mysql，一个canal server三个instance分别连接到这三台mysql；
现在一个canalsharp客户端能获取到三个instance的消息吗？

**Comment by stulzq** [comment]
不支持

**Comment by pinopino** [comment]
只能是1：1？

**Comment by stulzq** [comment]
你可以New多个 NewSingleConnector

**Comment by pinopino** [comment]
不好意思，能详细说明一下么？ 多个connector是一副怎样的结构？
多个connector连接到多个canal server 还是什么？

**Comment by stulzq** [comment]
开多个线程啊，每个线程一个 connector连接到不同canal server

**Comment by pinopino** [comment]
开不开线程不关心，搞进程也无所谓。只是想确定下这个结构而已，现在知道了，嗯，thx
