### ISSUE TITLE
客户端设置的filter不能覆盖掉服务端的filter信息

### ISSUE THREAD

**Issue by simendancer** [dotnetcore/CanalSharp#41]
connector.Subscribe("db.table");
这句话不会覆盖掉服务端设置的默认filter，无法做到监听指定库指定表的binlog变化，必须在服务端的instance.properties里设置才有效

**Comment by stulzq** [comment]
客户端的 filter 和服务端的关系，并不是覆盖。客户端 filter 是过滤服务端到客户端，而服务端filter过滤binlog，如果客户端filter不生效，那么考虑filter的值是无效的

**Comment by simendancer** [comment]
> 客户端的 filter 和服务端的关系，并不是覆盖。客户端 filter 是过滤服务端到客户端，而服务端filter过滤binlog，如果客户端filter不生效，那么考虑filter的值是无效的

我在服务端设置的是默认的全库全表，在客户端设置的是指定库指定表，但是读取到的还是全库全表的变化

**Comment by stulzq** [comment]
请提供你的部分代码

**Comment by simendancer** [comment]
> 请提供你的部分代码

- canal的配置基本都是默认值

# canal/conf/canal.properties
`canal.destinations = example`
`canal.conf.dir = ../conf`

# canal/conf/example/instance.properties
`canal.instance.master.address=xxx.xxx.xxx.xxx:3306`
`canal.instance.dbUsername=username`
`canal.instance.dbPassword=password`

`canal.instance.filter.regex=.*\\..*`
`canal.instance.filter.black.regex=`

# CanalSharp客户端代码
`var destination = "example";`
`var connector = CanalConnectors.NewSingleConnector("127.0.0.1", 11111, destination, "", "");`
`connector.Connect();`
`connector.Subscribe("ztuandb.tbztitem"); //指定库指定表`

- 运行之后，各个表的binlog都读出来了

**Comment by withlin** [comment]
hi @simendancer, 你能提供一下 canal server的版本吗？ 我本地测试，会覆盖服务端的测试。您可以提供一下你的canal-server的版本吗？ 还有就是mysql的版本。方便我排查问题。

**Comment by simendancer** [comment]
> hi @simendancer, 你能提供一下 canal server的版本吗？ 我本地测试，会覆盖服务端的测试。您可以提供一下你的canal-server的版本吗？ 还有就是mysql的版本。方便我排查问题。

canal 是1.1.3

**Comment by simendancer** [comment]
> hi @simendancer, 你能提供一下 canal server的版本吗？ 我本地测试，会覆盖服务端的测试。您可以提供一下你的canal-server的版本吗？ 还有就是mysql的版本。方便我排查问题。

canal 是1.1.3
mysql 是 阿里云RDS 5.6.16

**Comment by withlin** [comment]
[canal-FAQ](https://github.com/alibaba/canal/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)

>canal 1.1.3+版本之后,会在日志里记录最后使用的filter条件，可以对比使用的filter看看是否和自己期望的是一致，如果不一致检查一下第3步
c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter :

你可以看一下你的filter。然后贴出来我看一下?

**Comment by simendancer** [comment]
> [canal-FAQ](https://github.com/alibaba/canal/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94)
> 
> > canal 1.1.3+版本之后,会在日志里记录最后使用的filter条件，可以对比使用的filter看看是否和自己期望的是一致，如果不一致检查一下第3步
> > c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^._.._$
> > c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter :
> 
> 你可以看一下你的filter。然后贴出来我看一下?

# example.log
`2019-06-28 11:58:44.305 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example `
`2019-06-28 11:58:44.311 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$  //这是instance里的filter` 
`2019-06-28 11:58:44.312 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : `

# 客户端 CanalSharp-Debug-2019-06-28.txt
`2019-06-28 11:58:55.7165 | Canal connect success. IP: 127.0.0.1, Port: 11111 `
`2019-06-28 11:58:55.7292 | Subscribe success. Filter: data.test //这是客户端设置的filter 

# 客户端 test-Debug-2019-06-28.txt
`2019-06-28 11:58:55.3515 | Nlog enabled. `
`2019-06-28 11:58:55.7629 | ================> binlog[mysql-bin.000004:2058] ,name[data,taobaocategory] , eventType :Update  //运行之后，读到了data,taobaocategory的update`

- 跟filter有关的只有上面三个日志

**Comment by withlin** [comment]
您好确实有这个问题。但是这个问题不是我们客户端的问题。我用canal-1.0.26测试是可以的。您可以测试一下。

**Comment by simendancer** [comment]
> 您好确实有这个问题。但是这个问题不是我们客户端的问题。我用canal-1.0.26测试是可以的。您可以测试一下。

好的谢谢了，而且我发现1.1.3同步mysql到es也有很多奇怪的问题，准备试试1.0.26

**Comment by withlin** [comment]
我知道原因了,我尝试说清楚:
服务端instance.properties的配置:
```
//原始的配置是怕匹配所有的，但是我测试你应该随便给一个默认的。比如你的配置 data.test
canal.instance.filter.regex= .*\\..*
//然后就变成了下面的样子
canal.instance.filter.regex= data.test

```
下图是我的，我一开始是Wholesale.Sku，也就是我的第一个我红色框框 框住的那个。
至于第二个我框住的那个是我客户端传上去的，也就是我的客户端的Fliter传上去看了的，也就是Wholesale.StockTest
![image](https://user-images.githubusercontent.com/22409551/60323680-5e325d00-99b5-11e9-90e8-acc0b1b19de0.png)

![image](https://user-images.githubusercontent.com/22409551/60324002-24158b00-99b6-11e9-8d29-f3fd6d6bbe2c.png)
针对以上问题我们总结一下:
1.canal-server的配置不能用所有的配置： .*\\..*需要随便设置一个，即可处理你的问题了。(可能是服务端没有处理好，你可以去canal那边提个bug)。
2.说明我们的canal是没有问题的。

**Comment by simendancer** [comment]
> 我知道原因了,我尝试说清楚:
> 服务端instance.properties的配置:
> 
> ```
> //原始的配置是怕匹配所有的，但是我测试你应该随便给一个默认的。比如你的配置 data.test
> canal.instance.filter.regex= .*\\..*
> //然后就变成了下面的样子
> canal.instance.filter.regex= data.test
> ```
> 
> 下图是我的，我一开始是Wholesale.Sku，也就是我的第一个我红色框框 框住的那个。
> 至于第二个我框住的那个是我客户端传上去的，也就是我的客户端的Fliter传上去看了的，也就是Wholesale.StockTest
> ![image](https://user-images.githubusercontent.com/22409551/60323680-5e325d00-99b5-11e9-90e8-acc0b1b19de0.png)
> 
> ![image](https://user-images.githubusercontent.com/22409551/60324002-24158b00-99b6-11e9-8d29-f3fd6d6bbe2c.png)
> 针对以上问题我们总结一下:
> 1.canal-server的配置不能用所有的配置： .*\..*需要随便设置一个，即可处理你的问题了。(可能是服务端没有处理好，你可以去canal那边提个bug)。
> 2.说明我们的canal-client是没有问题的。

我刚试了一下
# instance.properties
`canal.instance.filter.regex=data.taobaocategory`
# 客户端
`connector.Subscribe("data.test");`

# 运行后
能读到data.taobaocategory的binlog
然后修改data.test的数据，没有任何反应
说明客户端的配置的没有覆盖成功
