### ISSUE TITLE
自动掉线的问题

### ISSUE THREAD

**Issue by HousionQ** [dotnetcore/CanalSharp#42]
就很简单用的Demo的东西，然后连着Canal平均一个多小时就和Canal断开连接了，跑的环境是在一个线程上跑，得到结果后，会在另一条线程通知出去，能够知道是什么原因吗？

**Comment by withlin** [comment]
您好，可以提供一下 canal server的版本,最好有复现的demo. 跑的在什么环境上的？ 操作系统等。

BTW,要学会问问题。
