### ISSUE TITLE
获取变更列的值是是乱码

### ISSUE THREAD

**Issue by longjiam** [dotnetcore/CanalSharp#43]
获取变更列的中文值是是乱码，canal（canal.deployer-1.1.4.tar.gz）服务端在centos 中运行，已经设置了canal.instance.connectionCharset = UTF-8。数据库也是utf8mb4。客户端在linux 和windows中获取的中文值均为乱码

**Comment by withlin** [comment]
你的表是什么编码？

**Comment by longjiam** [comment]
utf8mb4

**Comment by withlin** [comment]
你可以试试 java的客户端,我觉得是服务端的问题。

**Comment by longjiam** [comment]
已经ok了，服务端canal.instance.connectionCharset = GBK 就正常了

**Comment by longjiam** [comment]
创建一个群，好讨论问题涩

**Comment by withlin** [comment]
在issue 讨论就好了,BTW GBK 编码用的比较少吧. /close
