### ISSUE TITLE
[canal 1.1.3]经常出现该问题something goes wrong with channel

### ISSUE THREAD

**Issue by songhejia** [dotnetcore/CanalSharp#46]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
CanalSharp.Protocol.Exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x4d67f2df, /172.16.10.16:63064 => /172.16.10.16:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:database_dn1 should start first 在 CanalSharp.Client.Impl.SimpleCanalConnector.Subscribe(String filter) 在 GdkySyncService.canal_sync_job.DoSync(CancellationToken token, Bas_Datasource example) 位置 D:\projects\GDKY_Data_MS\GDKY_Data_MS\GdkySyncService\Jobs\Sync\canal_sync_job.cs:行号 154

经常出现该问题，需要删除meta.dat和h2.mv.db文件后，重启才能好，这是为啥呢？？？急急急

___
### Bug
- canal1.1.3
--mysql 5.7
--windows server2012

- What happen?
运行一段时间

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by withlin** [comment]
看样子是客户端断开连接，应该设置超时时间，并且做响应的处理，比如重连。

**Comment by stulzq** [comment]
需要根据Canal Server的日志来进行分析，CanalSharp 目前已经重构并适配最新版 Canal

**Comment by gdbd8341** [comment]
这个问题，解决了吗

**Comment by xiongwj13** [comment]
同问，解决了吗？我是在docker里面运行了canal-server然后再运行canal-adapter的时候出的问题
