### ISSUE TITLE
Debezium

### ISSUE THREAD

**Issue by MetSystem** [dotnetcore/CanalSharp#58]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of Canal-Server, OS ,Mysql?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by stulzq** [comment]
Canal-Server v1.1.6
Mysql:Determined by canal-server
