### ISSUE TITLE
Canal 服务端用kakfa 模式，不会启用11111端口，客户端却从11111端口取数据

### ISSUE THREAD

**Issue by lx4556332** [dotnetcore/CanalSharp#59]
Canal 服务端用kakfa 模式，不会启用11111端口，客户端却从11111端口取数据。

**Comment by withlin** [comment]
展示一下你的代码

**Comment by lqyxt** [comment]
我直接用了kafka都可以收到数据，用了这个客户端没法接收到数据，这个ClientId是不是就是Instance的SlaveId？

**Comment by withlin** [comment]
可能是版本问题，protocol 协议没有更新
